# Generated by Django 4.2.25 on 2025-10-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kanbanitem',
            name='kanban_kanb_board_i_382fb0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='kanbanitem',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='kanbanitem',
            index=models.Index(fields=['status', 'order'], name='kanban_kanb_status_87698a_idx'),
        ),
        migrations.RemoveField(
            model_name='kanbanitem',
            name='board',
        ),
        migrations.DeleteModel(
            name='KanbanBoard',
        ),
    ]
