# Generated by Django 4.2.24 on 2025-09-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kanbanitem',
            index=models.Index(fields=['board', 'status', 'order'], name='kanban_kanb_board_i_382fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='kanbanitem',
            index=models.Index(fields=['task_content_type', 'task_object_id'], name='kanban_kanb_task_co_cc9b9a_idx'),
        ),
    ]
