# Generated by Django 4.2.25 on 2025-10-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_remove_kanbanitem_kanban_kanb_board_i_382fb0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('on_hold', 'Hold'), ('review', 'Review'), ('done', 'Complete')], default='not_started', max_length=20),
        ),
    ]
