# Generated by Django 4.2.24 on 2025-09-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_kanbanitem_kanban_kanb_board_i_382fb0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('onhold', 'On Hold'), ('completed', 'Completed')], default='active', max_length=20)),
            ],
        ),
    ]
