# Generated by Django 4.2.25 on 2025-10-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete",
            field=models.BooleanField(
                default=False,
                help_text="Incomplete orders are still in the customer's cart.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_charge_id",
            field=models.CharField(
                blank=True, help_text="Auto-filled by Stripe", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True, help_text="Auto-filled by Stripe", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True, help_text="Auto-filled by Stripe", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_refund_id",
            field=models.CharField(
                blank=True, help_text="Auto-filled by Stripe", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Active prices are visible to customers"
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, help_text="Auto-filled by Stripe", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-filled by Stripe.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="latest_stripe_invoice_id",
            field=models.CharField(
                blank=True, help_text="Auto-filled by Stripe", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="next_payment_attempt",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-filled by Stripe if payment failed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-filled by Stripe",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
