# Generated by Django 5.2 on 2025-08-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthmetric',
            old_name='water',
            new_name='water_intake',
        ),
    ]
