# Generated by Django 5.2 on 2025-05-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="sub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("contract_type", models.CharField(default="NA", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
