# Generated by Django 4.1.13 on 2025-09-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_calendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(max_length=255),
        ),
    ]
