# Generated by Django 4.2.24 on 2025-09-29 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_family_familyinvite_familymembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthmetric',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='healthmetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
